---
title: "Article 2:" 
author:
  - name: Ver Hoeye Killian
    url: {} 
date: 10-28-2019
Output:
  distill::distill_article: 
    self_contained: false
---


## Vocabulary 

| Words from the text  | Synonym/explanation in English |
| -------------------  | ------------------------------ |
| A shrub              | A plant with a rounded shape formed from small branches growing directly from the ground |
| The understory       | A layer of plants that grows under the canopy of a forest |
| The forest canopy    | The branches that spread out at the top of a group of trees |
| A low-lying area     | An area at a level that is not higher than the level of the ocean |
| Marshes              | Grounds near a lake, a river or the sea that often floods |
| Northern bobwhite quail | A species of bird |
| Poorly               | Not well |
| Woodpecker           | A species of bird |
| To nest              | To build a nest or live in a nest |
| A nest               | A structure built by birds or insects to leave their eggs in to develop |
| To compound          | To make a problem |
| Occupancy            | Someone's use of a room for the purpose of living |
| Artifact             | An object that was made in the past |
| An informed decision | A decision with a lot of knowledge or information about something |
| Inland               | Away from the sea | 

## Analisis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | 
| Published in?                | 
| General topic?               | 
| Procedure/what was examined? | 
| Conclusions/discovery?       | 
| Remaining questions?         | 

