---
title: "Article 3 : Rising sea levels pose threat to homes of 300m people – study "
author:
  - name: Ver Hoeye Killian
    url: {}
date: 11-13-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

https://www.theguardian.com/environment/2019/oct/29/rising-sea-levels-pose-threat-to-homes-of-300m-people-study

# Vocabulary 

| Words from the text  | Synonym/explanation in English |
| -------------------  | ------------------------------ |
| To pose threat       | To cause a threat   |
| Strengthened         | Something made stronger  |
| The upward revision  | A revision with a higher level, value  |
| A sophisticated assessment  | A sophisticated estimation  |
| To compensate        | To fill in  |
| Misreadings          | Wrong readings |
| A shock              | Feeling because of an unpleasant surprise  |
| To reshape           | To redecide the form of something  |
| Eightfold            | Eight times more than somethin  |
| Subsiding            | Going down to a lower level  |
| CEO                  | A chief executive officer  |
| Flat land            | Land in a low level  |
| To assume            | To affirm  |
| RCP2.6               | Representative Concentration Pathway = a greenhouse gas concentration trajectory adopted by the IPCC. RCP 2.6 affirms that annual greenhouse gas emissions reach their highest level between 2010–2020 and then will decline |
| Pledges              | Promises  |
| Economic harm        | Economic damage  |
| The silver lining    | The silver layer  |

# Analysis table 
|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | -Scott Kulp : lead author of the study and senior scientist at Climate Central  -Benjamin Strauss : Climate Central’s chief scientist and chief executive officer |
| Published in?                | 10/30/2019 |
| General topic?               | The consequences of rising sea levels over human habitations. |
| Procedure/what was examined? | New more sophisticated methods permitted to know how much people are threatened by rising sea levels. An older study was already made by the NASA but the satellite underestimated the results because of tall buildings and trees. This is why the new study used an artificial intelligence to analyse the results. The scientists based their calculation on the scenario RCP2.6. |
| Conclusions/discovery?       | Scientists discovered that about 300 million people will be threatened by floodings at least once a year by 2050. Their results was very higher than the results of the NASA’s study. They found that the biggest changes due to the rising sea levels will occur in Asia. Indeed, the risks of flooding are much higher in few asiatic lands than in other places in the world. For instance, Jakarta (capital city of Indonesia) is subsiding thus it’s more subject to flooding. The scientists said that a big amount of human development occurs in low-lying land so it’s necessary to strengthen defenses against the tidewater rising. According to the study, the damages because of rising sea level could rise until 10<sup>12</sup> $ per year by 2050 |
| Remaining questions?         | According to the scientists, we need more sophisticated measurements to foresee an accurate estimation of the costs of damages caused by the rising sea level. |
