---
title: "Article 4: Climate change: UN panel signals red alert on 'Blue Planet'"
author:
  - name: Ver Hoeye Killian
    url: {}
date: 11-28-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

https://www.bbc.com/news/science-environment-49817804

# Vocabulary 

| Words from the text  | Synonym/explanation in English |
| -------------------  | ------------------------------ |
| Warns                | Dangers                        |
| To unleash           | To release                     |
| Hastening            | From the verb « to hasten ». It means that something happen sooner |
| To cope              | Dealing with difficulties      |
| In a nutshell        | Briefly                        |
| To soak up           | To absorb                      |
| Huge                 | Very wide                      |
| To gush              | To flow                        |
| Wealth               | Money                          | 
| Surge                | A sudden increase              |
| A shore              | A land along of a sea, a lake… |
| To highlight         | To attract attention to something |
| Megacities           | Cities with more than 10 billions inhabitants |
| Nasty                | Bad                            |
| Inland               | Away from the sea              |
| Sustainable          | Able to continue a long time   |
| To impair            | To reduce                      |
| The availability     | The disponibility              |
| Hydropower           | A power produce by the water’s energy |
| The onset            | The beginning of something     |
| Worn                 | Old and damaged                |
| Sharply              | To change suddenly and widly   |
| The livelihoods      | Means of living                |
| Manageable           | Possible                       |

# Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | -Dr Jean-Pierre Gattuso : co-ordinating lead author of the report. -Prof Debra Roberts : co-chair of an IPCC working group II. -Dr Nerilie Abram : from the Australian National University in Canberra. -Hoesung Lee : chair of the IPCC. -Intergovernmental Panel on Climate Change (IPCC). |
| Published in?                | 09/25/2019 |
| General topic?               | The climate changes including the rising sea levels that are threatening the Earth. |
| Procedure/what was examined? | The scientists examined the link between the climate changes like the rising of ocean’s temperatures or greenhouse gas effects and the sea level rise. More, they analysed the consequences of this sea level in the future. |
| Conclusions/discovery?       | Scientists have discovered that the oceans absorbed 90% of heat generated by humans. Because of this process, the water’s molecules take more places and it causes the rising of level. But actually this rising sea level is mainly causes by the melting of Antartica and Greenland’s glaciers. Indeed, these glaciers have lost a big amount of mass between 2007 and 2016 and it will continue melting. According to the authors, the sea level could rise until 1.1m by 2100. Beacause of all this extra water, some islands will become uninhabitable. But other places will be threaten too. For instance, megacities such as New York, Shangai or London. Then, scientists affirm that if humans reduce considerably their CO2 emissions it will be possible to manage consequences of the sea level but even in this scenario, people should be carefull. |
| Remaining questions?         | No |
